Output whats.gif

Set FontSize 18
Set Width 750
Set Height 422
Set Padding 20
Set TypingSpeed 100ms

Type "whats 3m in feet"
Sleep 200ms
Enter
Sleep 4s

Type "whats 10 RON in USD"
Sleep 200ms
Enter
Sleep 4s

Type "whats 10% of 200"
Sleep 200ms
Enter
Sleep 4s

Type "whats 100J in kWh"
Sleep 200ms
Enter
Sleep 4s

Type "whats 1024KiB in MiB"
Sleep 200ms
Enter
Sleep 4s

Type "whats 1.21 gigawatts in watts"
Sleep 200ms
Enter
Sleep 4s

Type "whats 3tbsp in L"
Sleep 200ms
Enter
Sleep 4s
