name: Release

on:
  push:
    tags:
      - '*'

jobs:

  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: mlugg/setup-zig@v1
      with:
        version: 0.14.0

    - run: zig build test


